export const VEHICLE_MAKES = [
  "Acura", "Audi", "BMW", "Buick", "Cadillac", "Chevrolet", "Chrysler", "Dodge",
  "Ford", "GMC", "Honda", "Hyundai", "Infiniti", "Jeep", "Kia", "Lexus",
  "Lincoln", "Mazda", "Mercedes-Benz", "Mercury", "Mini", "Mitsubishi", "Nissan",
  "Pontiac", "Porsche", "Ram", "Saturn", "Scion", "Subaru", "Tesla", "Toyota",
  "Volkswagen", "Volvo"
];

export const VEHICLE_MODELS: { [key: string]: string[] } = {
  Toyota: ["Camry", "Corolla", "RAV4", "Highlander", "Prius", "Tacoma", "Tundra", "4Runner", "Sienna", "Avalon", "C-HR", "Venza"],
  Honda: ["Civic", "Accord", "CR-V", "Pilot", "Odyssey", "HR-V", "Ridgeline", "Passport", "Insight", "Fit"],
  Ford: ["F-150", "Escape", "Explorer", "Mustang", "Edge", "Ranger", "Bronco", "Expedition", "Fusion", "Focus", "Mavericks"],
  Chevrolet: ["Silverado", "Equinox", "Malibu", "Traverse", "Tahoe", "Suburban", "Blazer", "Trax", "Colorado", "Camaro", "Corvette"],
  Nissan: ["Altima", "Sentra", "Rogue", "Maxima", "Pathfinder", "Frontier", "Murano", "Kicks", "Armada", "Titan"],
  BMW: ["3 Series", "5 Series", "7 Series", "X1", "X3", "X5", "X7", "M3", "M5", "i4", "iX"],
  Mercedes_Benz: ["C-Class", "E-Class", "S-Class", "GLA", "GLC", "GLE", "GLS", "A-Class", "CLA", "EQS"],
  Audi: ["A3", "A4", "A6", "Q3", "Q5", "Q7", "e-tron", "RS5", "RS7", "TT"],
  Lexus: ["ES", "IS", "LS", "NX", "RX", "UX", "GX", "LX", "RC", "LC"],
  Hyundai: ["Elantra", "Sonata", "Tucson", "Santa Fe", "Kona", "Palisade", "Venue", "Ioniq", "Accent"],
  Kia: ["Forte", "K5", "Sportage", "Telluride", "Sorento", "Soul", "Seltos", "Carnival", "Niro"],
  Subaru: ["Outback", "Forester", "Crosstrek", "Impreza", "Legacy", "Ascent", "WRX", "BRZ"],
  Volkswagen: ["Jetta", "Passat", "Tiguan", "Atlas", "Golf", "ID.4", "Taos", "Arteon"],
  Volvo: ["S60", "S90", "XC40", "XC60", "XC90", "V60", "V90", "C40"],
  Acura: ["TLX", "RDX", "MDX", "ILX", "NSX"],
  Infiniti: ["Q50", "Q60", "QX50", "QX60", "QX80"],
  Porsche: ["911", "Cayenne", "Macan", "Panamera", "Taycan"],
  Tesla: ["Model 3", "Model Y", "Model S", "Model X", "Cybertruck"],
  Jeep: ["Wrangler", "Cherokee", "Grand Cherokee", "Compass", "Renegade", "Gladiator"],
  Dodge: ["Charger", "Challenger", "Durango", "Journey"],
  Chrysler: ["300", "Pacifica", "Voyager"],
  Buick: ["Enclave", "Encore", "Envision"],
  Cadillac: ["CT4", "CT5", "XT4", "XT5", "XT6", "Escalade"],
  GMC: ["Sierra", "Terrain", "Acadia", "Yukon", "Canyon"],
  Ram: ["1500", "2500", "3500", "ProMaster"],
  Mini: ["Cooper", "Countryman", "Clubman"],
  Mitsubishi: ["Outlander", "Eclipse Cross", "Mirage"],
  Mazda: ["Mazda3", "Mazda6", "CX-30", "CX-5", "CX-9", "MX-5 Miata"],
  Lincoln: ["Navigator", "Aviator", "Nautilus", "Corsair"],
  Mercury: ["Grand Marquis", "Mariner", "Milan", "Mountaineer"],
  Pontiac: ["G6", "Grand Prix", "Solstice", "Torrent"],
  Saturn: ["Ion", "Vue", "Aura", "Sky"],
  Scion: ["tC", "xB", "xD", "FR-S"]
};